### ISSUE TITLE
How can I do the same Example without using WebPack?

### ISSUE THREAD

**Issue by ghost** [kweiberth/react-redux-todo-demo#1]
I have added script tags to my HTML::
    <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.3.1/redux.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-redux/4.4.1/react-redux.js"></script>
How can I make this example work without using Webpack and then Creating Bundles?

**Comment by kweiberth** [comment]
@mohak1990 it's going to be fairly difficult. Not sure I've seen it done too much. What is your reason for not using webpack?

You can include each React component as a script tag in your html, but you would have to write it in es5 and cannot use JSX. Also, I don't think you will be able to `require` anything into the files, which means you have to start writing all the components in one file, and include all dependencies in script tags in the html. The advantage of webpack and a build step is that you can transpile it, allowing you to use JSX and `require` statements to make you code more modular.
