### ISSUE TITLE
Redux Folder Structure

### ISSUE THREAD

**Issue by ghost** [kweiberth/react-redux-todo-demo#2]
Is the Folder Structure shown in to-do-list app a standard folder structure? Is it proper for bigger applications?

**Comment by kweiberth** [comment]
@mohak1990 it's hard to say if it's proper/standard. Folder structure is probably mostly preference. If I had to redo the folder structure on this app, I'd remove the "redux" folder and just make a folder for actions, reducers, store, etc. I'd also probably put all of the redux and components and containers folders into the client folder, or some time of "public" folder, meaning client-side stuff. The root folder would then be implicitly server-side stuff, and I could probably not have the "server" folder. Again, it's mostly just preference and as you scale you can re-evaluate the folder structure if it seems to not be logical or some folders contain too many or too few files.
